### ISSUE TITLE
Make path to lang servers configurable

### ISSUE THREAD

**Issue by oakad** [emacs-lsp/lsp-javascript#15]
It's not always feasible to require language servers to be available on the global path, in particular when the usual npm workflow is concerned.

Please consider making a path to the language server configurable via a variable or something.

**Comment by gpittarelli** [comment]
Sounds good, I'm thinking about this... I think we should probably solve this problem more generally for lsp-mode as a whole rather than make a one-off solution for lsp-javascript. Though that is what [lsp-haskell](https://github.com/emacs-lsp/lsp-haskell/blob/master/lsp-haskell.el#L20) did so if someone submits a PR for that I'd be up to merge it until we have a more general solution.

**Comment by oakad** [comment]
The problem with general solution is requirements mismatch. For example, lsp-javascript needs a single executable path, while lsp-java needs 2: a path to jvm being used and a path to an actual lsp implementation.

As to the actual immediate issue, going through full PR is a real hassle for such a small fix. That's what I've got right now:

```elisp
(unless (boundp 'lsp-javascript-typescript--server)
  (setq lsp-javascript-typescript--server "javascript-typescript-stdio"))
```
...
```elisp
(lsp-define-stdio-client lsp-javascript-typescript "javascript"
                         lsp-javascript-typescript--get-root (list lsp-javascript-typescript--server)
                         :ignore-messages '("readFile .*? requested by TypeScript but content not available")
                         :initialize 'lsp-javascript-typescript--initialize-client)
```

**Comment by gpittarelli** [comment]
Okay, I bit the bullet and did it for all 3 modes. I do think configuring exec-path is probably better for most typical usages, but just to give people options there are now `...-server` and `...-server-args` customizable options for each of the 3 modes.
