### ISSUE TITLE
lsp-ui issue

### ISSUE THREAD

**Issue by ztlevi** [emacs-lsp/lsp-javascript#16]
@gpittarelli @sebastiencs Looks like we have a couple commits recently. But it breaks the `lsp-ui` somehow. I tested under `python-mode` and nothing is wrong. So I guess it's neither `lsp-mode` or `lsp-ui`'s problem but `lsp-javascript`'s.

What I was trying to do is only put cursor under some keyword. And the `lsp-ui` broke up. Here is the backtrace. Also I don't have this kind of problem for the pervious version.
```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  string-match("\\(?:[ \011\n\015]+\\)\\'" nil)
  lsp-ui-doc--extract-marked-string(#<hash-table equal 2/65 0x45742c3d>)
  lsp-ui-doc--set-eldoc(#<hash-table equal 2/65 0x45742c3d>)
  lsp-ui-doc--filter-marked-string((#<hash-table equal 2/65 0x45742c3d> "**alias**"))
  lsp-ui-doc--extract((#<hash-table equal 2/65 0x45742c3d> "**alias**"))
  lsp-ui-doc--callback(#<hash-table equal 2/65 0x45742c1d> (249 . 258) #<buffer App.js>)
  #f(compiled-function (hover) #<bytecode 0x6057338d>)(#<hash-table equal 2/65 0x45742c1d>)
  lsp--parser-on-message(#s(lsp--parser :waiting-for-response nil :response-result nil :headers nil :body nil :reading-body nil :body-length nil :body-received nil :leftovers "" :queued-notifications nil :queued-requests nil :workspace #s(lsp--workspace :parser #1 :file-versions #<hash-table equal 1/65 0x5e9de3dd> :server-capabilities #<hash-table equal 15/65 0x5da0aab5> :registered-server-capabilities nil :root "/Users/tingzhou/Developer/cryptoground/frontend/" :client #s(lsp--client :language-id #f(compiled-function (_) #<bytecode 0x5e9b92e1>) :send-sync nil :send-async nil :type nil :new-connection #f(compiled-function (filter sentinel) #<bytecode 0x5e9b932d>) :stderr "*lsp-javascript-typescript stderr*" :get-root #f(compiled-function () #<bytecode 0x5e9b9111>) :ignore-regexps nil :ignore-messages ("readFile .*? requested by TypeScript but content not available") :notification-handlers #<hash-table equal 0/65 0x5e9b9339> :request-handlers #<hash-table equal 0/65 0x5e9bce2d> :response-handlers #<hash-table eql 224/325 0x5e9bd05d> :string-renderers (("javascript" . lsp-javascript-typescript--render-string) ("typescript" . lsp-javascript-typescript--render-string)) :last-id 235 :enable-function lsp-javascript-typescript-enable :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x5e9bd07d> :action-handlers #<hash-table equal 0/65 0x5e9bd09d>) :change-timer-disabled nil :proc #<process lsp-javascript-typescript> :cmd-proc #<process lsp-javascript-typescript> :buffers (#<buffer App.js>) :highlight-overlays #<hash-table eq 0/65 0x5e9de60d> :extra-client-capabilities nil :status nil :metadata #<hash-table equal 0/65 0x5e9de62d> :watches #<hash-table equal 0/65 0x5e9de64d>)) "{\"jsonrpc\":\"2.0\",\"id\":235,\"result\":{\"contents\":[{\"language\":\"typescript\",\"value\":\"import Component\"},\"**alias**\"],\"range\":{\"start\":{\"line\":7,\"character\":18},\"end\":{\"line\":7,\"character\":27}}}}")
  #f(compiled-function (proc output) #<bytecode 0x5e9df665>)(#<process lsp-javascript-typescript> "Content-Length: 191\015\n\015\n{\"jsonrpc\":\"2.0\",\"id\":235,\"result\":{\"contents\":[{\"language\":\"typescript\",\"value\":\"import Component\"},\"**alias**\"],\"range\":{\"start\":{\"line\":7,\"character\":18},\"end\":{\"line\":7,\"character\":27}}}}")
```

**Comment by gpittarelli** [comment]
I couldn't reproduce this error using emacs 25.3.1 running with `-Q` and current master of `lsp-ui`, `lsp-mode` and `lsp-javascript-typescript` and with `javascript-typescript-langserver@2.9.0`. I tried with these test files: https://github.com/gpittarelli/emacs-lsp-acceptance-testing/tree/83904e13fd2875c37fdc548ba1aea8ba98d40e3a/tests/fixtures/js 

Could you verify what versions you are running, and post a minimal snippet of code that reproduces this?

**Comment by ztlevi** [comment]
I'm using emacs 26.1, latest version of `lsp-javascript-typescript`, `lsp-ui` and `lsp-mode` with `javascript-typescript-langserver@2.9.0`. I tried the same file you tested here and it's still not working.


![kapture 2018-05-26 at 20 59 23](https://user-images.githubusercontent.com/16655096/40582348-4bd7a7da-6128-11e8-8b74-9238dc99bc94.gif)

**Comment by sebastiencs** [comment]
I also don't have this issue:
![peek 27-05-2018 06-38](https://user-images.githubusercontent.com/5273820/40582502-d3a9d160-6178-11e8-85fa-f7f647f9fab6.gif)

Can you try to delete all the lsp related packages and reinstall them ?

**Comment by ztlevi** [comment]
I tried reinstalling everything and tried on 25.3 as well but none of them works. I even roll back my personal emacs config's version. 

The problem is related with `lsp-ui`. Once I turned off `lsp-ui` mode, it will not show the error message.

**Comment by ztlevi** [comment]
My packages version:
`lsp-mode`: 20180518.2223
`lsp-ui`: 20180526.2113
`lsp-javascript-typescript` is pulled from Github.

Noted here, I have my global node bins installed under `~/.npm-global` and it's already added to the `exec-path`.

**Comment by ztlevi** [comment]
@gpittarelli  @sebastiencs  Could you guys double check [this line](https://github.com/emacs-lsp/lsp-javascript/blob/master/lsp-javascript-typescript.el#L55)? Once I comment out this line and corresponding functions, my `lsp-ui` works again.

**Comment by ztlevi** [comment]
After update the `lsp-ui` to version `20180604.244` the error disappear. But it's still there for React typescript project.

I created an [new issue](https://github.com/emacs-lsp/lsp-ui/issues/143) on `lsp-ui` project. I feel like it's the rendering problem with `lsp-ui` and maybe some of my markdown package setting.

**Comment by cmatzenbach** [comment]
@ztlevi I'm having a very similar issue to you, except disabling lsp-ui fixes it _mostly_, but not completely.  With lsp-ui mode enabled, everywhere I move I get the "error in process filter: Wrong type argument: arayp, nil" error.  When I disable lsp-ui, that does stop the error from occuring when you move over variables and functions and such, but did you try doing an autocompletion with company?  It seems to do fine, but if I type "doc", the "document" suggestion pops up in the company window, but as soon as I select it, I get the "error in process filter: Wrong type argument: arayp, nil" error again.  Is that not occurring for you?  If you try, I bet you'll find the same thing.

This made me realize that the problem probably doesn't actually lie in lsp-ui, but in this package (or maybe a related one?  maybe the langserver itself)?  Something isn't getting all the data from the server correctly, which I believe is the responsibility of this package - and that is what is messing up lsp-ui, and also messing up the lsp company completions.

Here's my relevant emacs config:
`
(use-package lsp-mode
  :defer t
  :config
  (require 'lsp-imenu)
  (add-hook 'lsp-after-open-hook 'lsp-enable-imenu))

(use-package lsp-ui
  :after lsp-mode
  :hook (lsp-mode . lsp-ui-mode))
(use-package company-lsp
  :after (lsp-mode company-mode)
  :custom (company-lsp-enable-recompletion t)
  :config (add-to-list 'company-backends 'company-lsp))

(use-package lsp-javascript-typescript
  :init
  ;; (add-hook 'js2-mode-hook 'lsp-mode)
  (add-hook 'js2-mode-hook 'company-mode)
  (add-hook 'js2-mode-hook #'lsp-javascript-typescript-enable)

  ;; (add-hook 'typescript-mode-hook 'lsp-mode)
  (add-hook 'typescript-mode-hook 'company-mode)
  (add-hook 'typescript-mode-hook #'lsp-javascript-typescript-enable)
  :config
  (defun my-company-transformer (candidates)
    (let ((completion-ignore-case t))
      (all-completions (company-grab-symbol) candidates)))
  (defun my-js-hook nil
    (make-local-variable 'company-transformers)
    (push 'my-company-transformer company-transformers))
  (add-hook 'js2-mode-hook 'my-js-hook)
  (add-hook 'typescript-mode-hook 'my-js-hook)
  )
`
I'm running emacs 26.1 (on Arch linux), and had just updated all the lsp-related packages to their newest versions from melpa.

Here's the full error log from emacs:
`
Debugger entered--Lisp error: (wrong-type-argument arrayp nil)
  replace-regexp-in-string("[\n\011 ]+" " " nil)
  lsp-ui-sideline--format-info(#<hash-table equal 2/65 0x1b655a5>)
  lsp-ui-sideline--push-info("document" 39 (1030 . 1038) #<hash-table equal 2/65 0x1d476a5>)
  #f(compiled-function (info) #<bytecode 0x1a000ad>)(#<hash-table equal 2/65 0x1d476a5>)
  lsp--parser-on-message(#s(lsp--parser :waiting-for-response nil :response-result nil :headers nil :body nil :reading-body nil :body-length nil :body-received nil :leftovers "" :queued-notifications nil :queued-requests nil :workspace #s(lsp--workspace :parser #1 :file-versions #<hash-table equal 1/65 0xdbe9e9> :server-capabilities #<hash-table equal 15/65 0xe8e6d1> :registered-server-capabilities nil :root "/home/matzy/Projects/rsna-image-viewer/" :client #s(lsp--client :language-id #f(compiled-function (_) #<bytecode 0xebefdd>) :send-sync nil :send-async nil :type nil :new-connection #f(compiled-function (filter sentinel) #<bytecode 0xebf029>) :stderr "*lsp-javascript-typescript stderr*<2>" :get-root #f(compiled-function () #<bytecode 0x139dd7d>) :ignore-regexps nil :ignore-messages ("readFile .*? requested by TypeScript but content not available") :notification-handlers #<hash-table equal 0/65 0xebf035> :request-handlers #<hash-table equal 0/65 0xebf1e1> :response-handlers #<hash-table eql 20/65 0xebf201> :string-renderers (("javascript" . lsp-javascript-typescript--render-string) ("typescript" . lsp-javascript-typescript--render-string)) :last-id 74 :enable-function lsp-javascript-typescript-enable :prefix-function nil :uri-handlers #<hash-table equal 0/65 0xdc309d> :action-handlers #<hash-table equal 0/65 0xdc3395>) :change-timer-disabled nil :proc #<process lsp-javascript-typescript<1>> :cmd-proc #<process lsp-javascript-typescript<1>> :buffers (#<buffer index.js>) :highlight-overlays #<hash-table eq 0/65 0xdbeb95> :extra-client-capabilities nil :status nil :metadata #<hash-table equal 0/65 0xdbebb5> :watches #<hash-table equal 0/65 0xdbebd5>)) "{\"jsonrpc\":\"2.0\",\"id\":74,\"result\":{\"contents\":[{\"language\":\"typescript\",\"value\":\"var document: Document\"},\"**var** _(ambient)_\"],\"range\":{\"start\":{\"line\":38,\"character\":8},\"end\":{\"line\":38,\"character\":16}}}}")
  #f(compiled-function (proc output) #<bytecode 0xea14d9>)(#<process lsp-javascript-typescript<1>> "Content-Length: 155\015\n\015\n{\"jsonrpc\":\"2.0\",\"method\":\"textDocument/publishDiagnostics\",\"params\":{\"uri\":\"file:///home/matzy/Projects/rsna-image-viewer/src/index.js\",\"diagnostics\":[]}}Content-Length: 37\015\n\015\n{\"jsonrpc\":\"2.0\",\"id\":73,\"result\":[]}Content-Length: 207\015\n\015\n{\"jsonrpc\":\"2.0\",\"id\":74,\"result\":{\"contents\":[{\"language\":\"typescript\",\"value\":\"var document: Document\"},\"**var** _(ambient)_\"],\"range\":{\"start\":{\"line\":38,\"character\":8},\"end\":{\"line\":38,\"character\":16}}}}")
`

**Comment by cmatzenbach** [comment]
I also tested in a plan .js file (the file above was typescript), and I encountered the exact same error.  I also updated the javascript-typescript-langserver package from npm and still ran into the same issues.  Not sure what else to try at the moment.

One more thing, while we're on the subject.  I had this working about a week ago, so I'm confused what went wrong since then.  But a bigger issue - even though it was working, it was horrendously slow.  Autocompletions took about 10-15 seconds to populate, sometimes it was choppy when moving the cursor over different variables...the main issue was how insanely slow the autocomplete was though.  It made it unfortunately unusable for me, the lag was so bad.  Does that have anything to do with this package, or is that solely an issue between javascript-typescript-langserver and company-lsp?

**Comment by ztlevi** [comment]
@cmatzenbach Could you wrap your code and backtrace with ``` tag?

Looks like you have the problem with the sideline. You can try to disable that by setting `  (setq lsp-ui-sideline-enable nil)` and see if you have the same problem with the `lsp-ui-doc`.

And most likely it's due to the rendering method `lsp-javascript-typescript--render-string` and `lsp-typescript--render-string`. I tried the recent updates but it still fails.

I took a look at the `lsp-rust` and they have a slightly different approach:
```emacs lisp
(defun lsp-rust--render-string (str)
  (condition-case nil
      (with-temp-buffer
	(delay-mode-hooks (rust-mode))
	(insert str)
	(font-lock-ensure)
	(buffer-string))
    (error str)))
```
I don't know why we have `typescript-mode` [here](https://github.com/emacs-lsp/lsp-javascript/blob/master/lsp-javascript-typescript.el#L64) since it's enabled for `javascript-mode` too.

**Comment by gpittarelli** [comment]
@ztlevi Good point about lsp-rust's different technique, I've switched to that.

I agree its a bit awkward using `typescript-mode` everywhere but its the quick solution we have until we figure out a better alternative... typescript-mode is listed as a dependency so (hopefully?) package-install should grab it for you.

**Comment by cmatzenbach** [comment]
@ztlevi Thanks - fixed :)  I'm used to just writing in org and having it convert to markdown for me

**Comment by ztlevi** [comment]
@gpittarelli I just updated the package while I found the `lsp-ui-doc` only work for those functions have dedicated documents. But I don't have it for those undocumented funcitons.

For example.

I have it for `rudux`'s function `createStore` since it is documented.
![image](https://user-images.githubusercontent.com/16655096/41449091-e25cd870-7013-11e8-9ad7-bcbcc1e63074.png)
![image](https://user-images.githubusercontent.com/16655096/41449313-40e1d674-7015-11e8-9500-3af36b5257af.png)


While I don't have `lsp-ui-doc` for those undocumented functions.

- React-Dom
![image](https://user-images.githubusercontent.com/16655096/41449161-41de7f24-7014-11e8-8f81-988cb41dd90a.png)
![image](https://user-images.githubusercontent.com/16655096/41449173-50a429e6-7014-11e8-8299-523f901d20e8.png)

- React
![image](https://user-images.githubusercontent.com/16655096/41449213-8d244338-7014-11e8-9201-3cb7ce5ca025.png)
![image](https://user-images.githubusercontent.com/16655096/41449216-939a0c20-7014-11e8-9d17-2c2d4a1ec5d0.png)

**Comment by gpittarelli** [comment]
What do you expect lsp-ui-doc to show for something without docs? This sounds like an issue with the language server, not lsp-javascript

**Comment by ztlevi** [comment]
@gpittarelli For example in vscode, when I hover over a function it shows the function description.
![image](https://user-images.githubusercontent.com/16655096/41493842-9b459ce4-70c0-11e8-96bc-cb66aa5840d6.png)

And I think we have this feature before if you roll back the `lsp-javascript-typescript` version.

For example:
![image](https://user-images.githubusercontent.com/16655096/41493898-2ed44320-70c1-11e8-8515-785b0674e27e.png)
It shows the function's definition even there is no doc for this function in the mini buffer while it's gone in the `lsp-ui-doc`.

**Comment by gpittarelli** [comment]
I checked and I do get shown those function signatures, using latest master of lsp-mode and lsp-javascript-typescript

`M-x version RET` gives me `GNU Emacs 26.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2018-05-28`

I'm using this test file: https://github.com/gpittarelli/emacs-lsp-acceptance-testing/blob/master/tests/fixtures/js/a.js

With these as the only two config files: (running with `emacs -Q`)
  - https://github.com/gpittarelli/emacs-lsp-acceptance-testing/blob/master/tests/setup.el
  - https://github.com/gpittarelli/emacs-lsp-acceptance-testing/blob/master/tests/lsp-javascript-typescript.el

**Comment by cmatzenbach** [comment]
I can confirm @gpittarelli

**Comment by ztlevi** [comment]
@gpittarelli @cmatzenbach I also confirm the settings above and tests works. But the problem is, I enabled multiple backends at once. [Issue here](https://github.com/emacs-lsp/lsp-javascript/issues/18), once I add `(add-hook 'js-mode-hook #'lsp-typescript-enable)` to the setting. The module import works perfectly but the `lsp-ui-doc` broke up.

We can only enable one lsp for one mode and not allowed to do the following settings, right?
```
  (require 'lsp-javascript-typescript)
  (require 'lsp-javascript-flow)
  (require 'lsp-typescript)

  (add-hook 'js-mode-hook #'lsp-javascript-typescript-enable)
  (add-hook 'js-mode-hook #'lsp-typescript-enable)
  (add-hook 'js-mode-hook #'lsp-javascript-flow-enable)

  (add-hook 'js2-mode-hook #'lsp-javascript-typescript-enable) ;; for js2-mode support
  (add-hook 'js2-mode-hook #'lsp-javascript-flow-enable) ;; for js2-mode support
  (add-hook 'js2-mode-hook #'lsp-typescript-enable) ;; for js2-mode support

  (add-hook 'rjsx-mode-hook #'lsp-javascript-typescript-enable) ;; for rjsx-mode support
  (add-hook 'rjsx-mode-hook #'lsp-javascript-flow-enable) ;; for rjsx-mode support
  (add-hook 'rjsx-mode-hook #'lsp-typescript-enable) ;; for rjsx-mode support

  (add-hook 'typescript-mode-hook #'lsp-javascript-typescript-enable) ;; for typescript support
```
Is there any one for all solution here?

**Comment by cmatzenbach** [comment]
@ztlevi I definitely don't think you should be enabling them all at once.  They are all different langservers being developed, and the author of this package simply wrote bindings for all of them, meaning you're free to use whichever you want.  However, you're not supposed to enable more than one - they each do the same thing.  I have no idea how company and lsp and other packages are supposed to handle three different backends throwing the same (or very similar, depending on implementation) at them.  Just try with lsp-javascript-typescript and javascript-typescript-langserver.  I tried the typescript-langserver and it was really slow and not nearly as good.  I don't use flow so I didn't bother using that one.  Also, you can't use typescript and flow together, so why would you enable both?

**Comment by ztlevi** [comment]
@cmatzenbach [Issue here](https://github.com/emacs-lsp/lsp-javascript/issues/18), once I add (add-hook 'js-mode-hook #'lsp-typescript-enable) to the setting. The module import works perfectly but the lsp-ui-doc broke up.

**Comment by gpittarelli** [comment]
You definitely should only be enabling 1 language server at a time. I have no clue what will happen if you try to use multiple at once... If one of the language servers isn't doing something you want, you should raise the issue with that language server; there's not much we can do about it here.

**Comment by ztlevi** [comment]
Ok. Thanks! I will open issues on their repo later.
