### ISSUE TITLE
module completion not as expected

### ISSUE THREAD

**Issue by ztlevi** [emacs-lsp/lsp-javascript#18]
It's so weird that `lsp-javascript` does not have the full understanding of `react` package.

- Emacs
For the following case, I can jump to the `createSagaMiddleware` definition but neither `React`, `ReactDom` is working. But we are able to jump to the package file by jumping to the definition on `'react'`,`'react-dom'`. 
```
import React from 'react';
import ReactDOM from 'react-dom';
import createSagaMiddleware from 'redux-saga';
```

We are also not able to auto-complete `React.|` ( | is the cursor) using the importing syntax showing above. But it's working for importing syntax like this `import * as React from 'react';`
![image](https://user-images.githubusercontent.com/16655096/40881007-ccee60aa-6670-11e8-8c9d-62337b5fb241.png)

![image](https://user-images.githubusercontent.com/16655096/40881004-c180a958-6670-11e8-8686-037a7835c006.png)

- Vscode
While the observed behavior in vscode is both importing syntax should work. Jumping to definition on `React`, `ReactDOM` are working as well.
![image](https://user-images.githubusercontent.com/16655096/40881024-25cda21c-6671-11e8-8a26-a4ae979e7a04.png)

![image](https://user-images.githubusercontent.com/16655096/40880995-883862e4-6670-11e8-8bc4-03c0bfc25148.png)

Any ideas on this wierd behavior?

**Comment by gpittarelli** [comment]
Hi, thanks for the report.

> We are also not able to auto-complete React.| ( | is the cursor) using the importing syntax showing above. But it's working for importing syntax like this import * as React from 'react';

I think this is expected, intended (and really confusing!) TypeScript behavior; I believe you need `--allowSyntheticDefaultImports`. See https://www.typescriptlang.org/docs/handbook/compiler-options.html and the discussion here https://github.com/Microsoft/TypeScript-React-Starter/issues/8

I'm not totally sure how VS Code is doing it; maybe they have some secret sauce logic where they assume `--allowSyntheticDefaultImports`. I don't think this is something we can or should fix on our side... If you can reliably replicate that behavior I would raise the issue with https://github.com/sourcegraph/javascript-typescript-langserver

**Comment by ztlevi** [comment]
[VScode's lsp-javascript plugin] only have `javascript-typescript-langserver` as the language server although it is just an alternative. I don't know where can we find the vscode's built-in language-server and if it is available to use in Emacs. Thanks.

**Comment by ztlevi** [comment]
Yes, it works for typescript React project.

 And BTW, we don't have tsconfig.json for

**Comment by ztlevi** [comment]
Yes, we can reliably replicate this behavior. Make sure we just follow the steps under `lsp-javascript` to properly install all the packges and add hooks for different modes.

1. create a test react project.
```
npx create-react-app my-app
```
2. cd into it and edit `src/App.js`

- No completion found
![image](https://user-images.githubusercontent.com/16655096/41391265-772cc9cc-6f4e-11e8-897f-a7d9cad23b7c.png)
- Found completion
![image](https://user-images.githubusercontent.com/16655096/41391288-8e12c2b8-6f4e-11e8-819b-1b135a923650.png)

According to their [compile options](https://github.com/sourcegraph/javascript-typescript-langserver/blob/master/tsconfig.json_
), they are not using `allowSyntheticDefaultImports`. Since they use vscode languagers as dependencies, they should at least have the feature embeded but not enabled.

Furthurmore, I don't understand why we need `typescript-languager-server`. But we do need it to enable some module completion, take a look at some discussion [here](https://github.com/syl20bnr/spacemacs/pull/10795#issuecomment-394188335). This feature also should come with `javascript-typescipt-langserver`.

**Comment by ztlevi** [comment]
And what's more is we probably can have a better `company-transformer` function since the company list is handled by language server. Take a look at the code completion in vscode. @sebastiene cs

Thanks! I would like to try to implement this feature while I'm not yet lispy enough to do so 😂

![image](https://user-images.githubusercontent.com/16655096/41392993-9a77dc1e-6f58-11e8-920b-422b4cb644d5.png)

![image](https://user-images.githubusercontent.com/16655096/41392784-a191cdee-6f57-11e8-8cf4-5389fc378a21.png)
