### ISSUE TITLE
Completion does not work

### ISSUE THREAD

**Issue by terlar** [emacs-lsp/lsp-javascript#3]
Every time I try to complete something I get the following error message spammed:

```
Request failed: ((args-out-of-range #s(url http nil nil 127.0.0.1 35837 / nil nil nil nil t) 12))
```

Any idea where this error stems from? Seeing this package not doing very much, I suspect there might be something either in the `lsp-mode` package or in the node module?

**Comment by vibhavp** [comment]
Can you enable debugging with <kbd>M-x</kbd> `(toggle-debug-on-error)` and paste the resulting backtrace too?

**Comment by terlar** [comment]
I had debugging enabled through that, but didn't get any backtrace

**Comment by terlar** [comment]
Looks like it might have been my fault, I had forgot to remove some `tern`-related packages from loading.

**Comment by brorbw** [comment]
@terlar any chance you can remember what tern related packages?

**Comment by terlar** [comment]
I were using some Emacs tern packages and I removed all of those. However looking at this error now, it seems like it could also be that the `lsp-javascript-typescript` Emacs package was byte-compiled to a previous version of `lsp-mode`. Have you tried re-byte-compile both of these packages?
