### ISSUE TITLE
Flow support causing constant logging

### ISSUE THREAD

**Issue by bruce** [emacs-lsp/lsp-javascript#7]
I'm seeing messages like the following being constantly logged in `*Messages*` (and being pretty distracting, popping up in the minibuffer)

`[2018-04-02 20:21:56.912] [INFO] nuclide-commons/process - 30ms: /home/bruce/.local/share/flow/bin/0.66.0/flow status --retry-if-init false --retries 0 --no-auto-start --from nuclide`

Are these messages useful? Is there any way to suppress these?

**Comment by bruce** [comment]
At first glance, btw, flow support seems to be working fine otherwise (I'm seeing documentation, for instance). Thanks!

**Comment by gpittarelli** [comment]
I'd recommend adding an ignore regex to `lsp-javascript-flow.el`, such as https://github.com/emacs-lsp/lsp-javascript/blob/master/lsp-javascript-typescript.el#L38

If that works, a PR would be appreciated :)

**Comment by bruce** [comment]
@gpittarelli Thanks for the quick response; I'd be happy to!

I'm not 100% certain that the logging is normal behavior (eg, just normal polling and not something related to a failure we should care about), but I'll do what you suggest and submit a PR if it appears to work as it should.

(In the meantime, perhaps @osener might have some feedback on the behavior itself.)
